- name: Server Playbook
  hosts: CockpitServers
  tasks:
    - name: Stop Unattended upgrades (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.service:
        name: unattended-upgrades
        state: stopped
      become: true

    - name: Full Apt upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
      become: true

    - name: Install cockpit
      ansible.builtin.apt:
        name: cockpit
        state: present
      become: true

    - name: Install podman
      ansible.builtin.include_tasks: tasks/Podman_Install.yaml

    - name: Reboot
      ansible.builtin.reboot:
      become: true
