- name: Install and setup Zigbee2MQTT
  hosts: ZigbeeNodes
  vars:
    apt:
      upgrade: true
  tasks:

    - name: Perform apt update/upgrade
      ansible.builtin.apt:
        update_cache: true
        upgrade: {{ apt.upgrade }}
      become: true

    - name: Reboot system after upgrade
      when: apt.upgrade
      ansible.builtin.reboot:
      become: true

    - name: Downloading nodejs binary
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/setup_lts.x
        dest: /temp/setup_lts.x
        mode: a+r
      become: true

    - name: Executing nodejs binary
      ansible.builtin.command:
        cmd: bash ./temp/setup_lts.x
      become: true

    - name: Install Apt dependencies
      ansible.builtin.apt:
        name:
          - nodejs
          - git
          - make
          - g++
          - gcc
          - libsystemd-dev
      become: true

    - name: Install Npm depependencies
      community.general.npm:
        global: true
        name: pnpm
      become: true

    - name: Create Zigbee2MQTT directory
      ansible.builtin.file:
        path: /opt/zigbee2mqtt
        state: directory
        owner: '{{ ansible_user_id }}'
      become: true
    
    - name: Pull Zigbee2Mqtt from git
      ansible.builtin.git:
        repo: https://github.com/Koenkk/zigbee2mqtt.git
        dest: /opt/zigbee2mqtt
        depth: 1

    - name: Install more dependencies
      ansible.builtin.command:
        chdir: /opt/zigbee2mqtt
        cmd: pnpm i --frozen-lockfile

    - name: Transfering Zigbee2Mqtt config
      ansible.builtin.copy:
        src: ./Zigbee2Mqtt/configuration.yaml
        dest: opt/zigbee2mqtt/configuration.yaml
        force: true

    - name: Transfering systemd config
      ansible.builtin.copy:
        src: ./Zigbee2Mqtt/zigbee2mqtt.service
        dest: /etc/systemd/system/zigbee2mqtt.service
      become: true

    - name: start Zigbee2Mqtt
      ansible.builtin.systemd_service:
        name: zigbee2mqtt
        state: started
