- name: Check if podman is installed
  ansible.builtin.command:
    cmd: "dpkg-query -W -f='${Status}' podman"
  register: podman_installed
  changed_when: false
  failed_when: false
  become: true

- name: Install Podman
  when: podman_installed.stdout != "install ok installed"
  ansible.builtin.include_tasks: tasks/Podman_Install.yaml

- name: Create config directory
  ansible.builtin.file:
    state: directory
    path: ./Zigbee2Mqtt
    mode: '777'

- name: Tranfer config
  ansible.builtin.copy:
    remote_src: true
    src: ./Rpi/Zigbee2Mqtt/configuration.yaml
    dest: ./Zigbee2Mqtt/configuration.yaml
    mode: '777'

- name: Pull Zigbee2Mqtt Image from ghcr.io
  containers.podman.podman_image:
    name: ghcr.io/koenkk/zigbee2mqtt
    tag: latest
  retries: 5

- name: Setup and start container
  containers.podman.podman_container:
    name: Zigbee2Mqtt
    image: ghcr.io/koenkk/zigbee2mqtt
    ports:
      - 8080:8080
    device:
      - /dev/ttyACM0:/dev/ttyACM0
    volume:
      - /run/udev:/run/udev:ro
      - '{{ ansible_user_id }}/data:/app/data'
    timezone: Europe/Copenhagen
    restart_policy: on-failure
    state: started
    detach: true
