# Minimal configuration.yml example
permit_join: true
mqtt:
    client_id: 'MY_CLIENT_ID'
    server: mqtt://localhost:1883
    user: my_user
    password: my_password
    version: 4
serial:
    # Could be either USB port (/dev/ttyUSB0), network Zigbee adapters (tcp://192.168.1.1:6638) or mDNS adapter (mdns://my-adapter).
    adapter: zboss
    port: /dev/ttyACM0
# Will run frontend on port 8080
frontend:
    enabled: true
advanced:
    pan_id: GENERATE
    ext_pan_id: GENERATE
    network_key: GENERATE